# Generated by Django 6.0.4 on 2026-06-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_mod_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mods/'),
        ),
        migrations.AddField(
            model_name='mod',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
